<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
if(!empty($errorMsg)){
    print "<div class=\"errors\">$errorMsg</div>";
}
?>
<div class="reportContainer">
    <?php 
    $reportID = $_GET['r'];
    if($reportID !=""){
        $objReports->viewMyReport($reportID);
    }
    else{
        $entryupdatemessage = "<p class=\"confirm\">Sorry, no report ID Specified.</p>";
    }
    ?>
    
    
</div>
<div class="reportContainer">
    <p>
        Report Generated by Kongreg8, <?php echo date('H:i:s d-m-Y'); ?> 
    </p>
</div>
